### ISSUE TITLE
同一条消息如何发送给多个通知渠道？

### ISSUE THREAD

**Issue by songjiayang** [binatify/prometheus#4]
配置参数如下：
```
receivers:
- name: 'my-recevier'
  webhook_configs:
  - url: 'https://hooks.pubu.im/services/g6r9n6nlwvmns42'
  email_configs:
  - to: 'xx@xxxx'
    auth_username: 'xxx'
    auth_password: 'xxx'
```

参考链接： [sending-alert-notifications-to-multiple-destinations](https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations/)
